import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Chakra from "@/components/Chakra";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "MIET MATERIAL PORTAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="icon" href="/favicon.ico" />
      <Chakra>
        {children}
      </Chakra>
        </body>
    </html>
  );
}
